on:
  push:
    branches:
      - main
  pull_request:

name: CI

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@908c540300062bd5a7e473851cdb4282204cee09 # v1.9.1
        with:
          version: stable
      - name: Show Forge version
        run: |
          forge --version
      - name: Run Forge build
        run: |
          forge build --sizes
      - name: Run Forge tests
        run: |
          make test
      - name: Run Forge tests with coverage
        run: |
          make coverage
